version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weighted_deepwalk
    volumes:
      - ./volume/Node Embeddings:/app/Node Embeddings
      - ./volume/Weighted Edges:/app/Weighted Edges